# Conceitos básicos de NumPy
***

O NumPy é uma biblioteca do Python que é amplamente usada para análise de dados, especialmente quando se trabalha com matrizes e arrays multidimensionais. O NumPy oferece muitas funções para operações em arrays, como soma, subtração, multiplicação, divisão e muito mais.

### Importação da biblioteca

In [3]:
import numpy as np

### Criar um array NumPy simples

Em programação, um array é uma coleção de elementos do mesmo tipo, que são armazenados em uma sequência contígua na memória. Em outras palavras, é uma estrutura de dados que contém um conjunto de valores do mesmo tipo.

No NumPy, um array é um objeto multidimensional que pode conter elementos de diferentes tipos. Arrays NumPy são geralmente mais eficientes e poderosos do que listas do Python, pois permitem operações matemáticas eficientes em grande quantidade de dados.

In [4]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


### Acessar os elementos em um array
Os índices em NumPy começam em 0. Por exemplo, para acessar o segundo elemento do array acima, você pode usar o índice 1,

In [9]:
# Acessar o segundo elemento do array
print(arr[1])

2


In [10]:
# Acessar o último elemento do array
print(arr[-1])

3


### Alterar o formato de um array 
 Nesse exemplo criamos um array unidimensional com seis elementos e, em seguida, o convertemos em um array bidimensional com duas linhas e três colunas:

In [18]:
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)
print(f'Array unidimensional: {arr}\n')
print(f'Array bidimensional:\n{new_arr}')

Array unidimensional: [1 2 3 4 5 6]

Array bidimensional:
[[1 2 3]
 [4 5 6]]


In [22]:
#Acessar o segundo elemento do array
new_arr[0,1]

2

In [24]:
#Acessar o segundo elemento do array
new_arr[-1,1]

5

### Operações aritméticas em arrays NumPy

In [26]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = arr1 + arr2
print(result)

[5 7 9]


In [27]:
result = arr1 * arr2
print(result)

[ 4 10 18]


In [30]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])


print(f'Array a:\n {a}\n')
print(f'Array b:\n {b}\n')


# Multiplicando os arrays
c = a * b

# Imprimindo o resultado
print(c)

Array a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array b:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [33]:
a[[0,2], [2,0]]

array([3, 7])