# Funções do NumPy
***

O NumPy possui diversas funções que facilitam a manipulação e análise de dados em arrays multidimensionais. Nesse notebook vamos demonstrar algumas delas. 

### Importação da biblioteca

In [2]:
import numpy as np

### np.arange()
Cria um array com valores sequenciais em um intervalo especificado;

In [11]:
# cria um array com valores sequenciais de 0 a 9
a = np.arange(10)
print(f'Array sequencial: {a}\n') 

# cria um array com valores sequenciais de 1 a 10
b = np.arange(1, 11)
print(f'Array sequencial iniciando com 1: {b}\n') 

# cria um array com valores sequenciais de 0 a 10, com intervalo de 2
c = np.arange(0, 11, 2)
print(f'Array sequencial com intervalo de 2: {c}\n') 

Array sequencial: [0 1 2 3 4 5 6 7 8 9]

Array sequencial iniciando com 1: [ 1  2  3  4  5  6  7  8  9 10]

Array sequencial com intervalo de 2: [ 0  2  4  6  8 10]



### np.zeros()
Cria um array preenchido com zeros;

In [18]:
# cria um array com 3 elementos preenchidos com zeros
a = np.zeros(3)
print(f'Array preenchidos com 0 : {a}\n') 

# cria um array bidimensional com 2 linhas e 3 colunas preenchido com zeros
b = np.zeros((2, 3))
print(f'Array bidimencional com 0:\n {b}') 

Array preenchidos com 0 : [0. 0. 0.]

Array bidimencional com 0:
 [[0. 0. 0.]
 [0. 0. 0.]]


### np.ones()
Cria um array preenchido com uns;

In [20]:
a = np.ones(4)
print(f'Array preenchidos com 1 : {a}\n') 

# cria um array bidimensional com 2 linhas e 3 colunas preenchido com uns
b = np.ones((2, 3))
print(f'Array preenchidos com 0:\n {b}') 

Array preenchidos com 1 : [1. 1. 1. 1.]

Array preenchidos com 0:
 [[1. 1. 1.]
 [1. 1. 1.]]


### np.eye()
Cria uma matriz identidade;

Uma matriz identidade é uma matriz quadrada em que todos os elementos da diagonal principal são iguais a 1 e todos os outros elementos são iguais a 0.

In [25]:
a = np.eye(3)
print(f'Matriz identidade 3x3:\n {a}\n') 


# cria uma matriz identidade 4x4
b = np.eye(4)
print(f'Matriz identidade 4x4:\n {b}\n') 


Matriz identidade 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matriz identidade 4x4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



### np.random.rand()
Gera um array com valores aleatórios entre 0 e 1.

In [73]:
# Gera um array de shape (2,3) com valores aleatórios entre 0 e 1
arr = np.random.rand(2,3)

print(arr)

[[0.0683622  0.75461628 0.22838936]
 [0.90889887 0.87088562 0.74732836]]


### np.random.randn()
Gera um array com valores aleatórios seguindo uma distribuição normal.

In [120]:
# Gera um array de shape (3,4) com valores aleatórios seguindo uma distribuição normal
arr = np.random.randn(3,4)
print(arr)

[[-1.67474458 -0.51805187 -1.39183226 -0.447756  ]
 [-1.32158197 -0.66532406  0.78770278 -1.74921063]
 [-0.14928697 -2.10942948  0.70209665 -0.6132478 ]]


In [61]:
arr_reshape[0]

array([0, 1, 2])

### np.reshape()
Modifica a forma de um array.

In [54]:
# Cria um array de shape (3,4)
arr = np.arange(12).reshape(2,6)

# Muda a forma do array para (4,3)
arr_reshape = np.reshape(arr, (4,3))

print(arr)
print('\n')

print(arr_reshape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### np.transpose()
Transpõe um array.

In [67]:
# Cria um array de shape (2,3)
arr = np.array([[1,2,3],[4,5,6]])

# Transpõe o array
arr_transpose = np.transpose(arr)

print(f'Array 2x3:\n{arr}')

print(f'\nTransposição do array:\n{arr_transpose}')

Array 2x3:
[[1 2 3]
 [4 5 6]]

Transposição do array:
[[1 4]
 [2 5]
 [3 6]]


### np.concatenate()
Concatena arrays.

In [102]:
# Cria dois arrays de shape (2,2)
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])


# Concatena os arrays ao longo do eixo das colunas
arr_concat = np.concatenate((arr1,arr2), axis=1)

print(f'Array 1:\n {arr1}\n')
print(f'Array 2:\n {arr2}\n')


print(f'Array concatenado:\n {arr_concat}')

Array 1:
 [[1 2]
 [3 4]]

Array 2:
 [[5 6]
 [7 8]]

Array concatenado:
 [[1 2 5 6]
 [3 4 7 8]]


### np.split()
Divide um array em partes.

In [107]:
# Cria um array de shape (4,)
arr = np.array([1,2,3,4])

# Divide o array em duas partes
arr_split = np.split(arr,2)

print(arr_split)

[array([1, 2]), array([3, 4])]


### np.max()
A função np.max() retorna o valor máximo de um array.

In [109]:
# Cria um array unidimensional com 5 elementos
arr = np.array([1, 4, 2, 5, 3])

# Retorna o valor máximo do array
maximo = np.max(arr)

# Imprime o valor máximo do array
print(f'O valor mínimo do array é: {maximo}')

O valor mínimo do array é: 5


### np.min()
A função np.min() retorna o valor mínimo de um array.

In [110]:
# Cria um array unidimensional com 5 elementos
arr = np.array([1, 4, 2, 5, 3])

# Retorna o valor mínimo do array
minimo = np.min(arr)

# Imprime o valor mínimo do array
print(f'O valor mínimo do array é: {minimo}')

O valor mínimo do array é: 1


### np.mean()
A função np.mean() retorna a média dos valores em um array.

In [114]:
# Cria um array unidimensional com 5 elementos
arr = np.array([1, 4, 2, 5, 3])

# Retorna a média do array
media = np.mean(arr)

# Imprime a média do array
print(f'A média dos elementos do array é: {media}')

A média dos elementos do array é: 3.0


### np.std()
A função np.std() retorna o desvio padrão dos valores em um array.

In [115]:
# Cria um array unidimensional com 5 elementos
arr = np.array([1, 4, 2, 5, 3])

# Retorna o desvio padrão do array
desvio_padrao = np.std(arr)

# Imprime o desvio padrão do array
print(f'O desvio padrão dos elementos do array é: {desvio_padrao}')

O desvio padrão dos elementos do array é: 1.4142135623730951


### np.sum()
A função np.sum() retorna a soma dos valores em um array.

In [116]:
# Cria um array unidimensional com 5 elementos
arr = np.array([1, 4, 2, 5, 3])

# Retorna a soma do array
soma = np.sum(arr)

# Imprime a soma do array
print(f'A soma dos elementos do array é: {soma}')

A soma dos elementos do array é: 15
