# Análise de vendas
***

*Contexto*: 
   
Uma empresa de varejo acaba de abrir uma nova filial em uma cidade e está em fase de avaliação. Para isso, foram  escolhidos quatro produtos que estão sendo vendidos na loja e foi realizado um registro diário das vendas ao longo de uma semana. A intenção é utilizar o NumPy para analisar as vendas da semana, identificar padrões e tomar decisões estratégicas com base nos resultados.

Os dados foram coletados e armazenados em uma matriz 5x4, onde cada linha representa um dia da semana e cada coluna representa um produto. O objetivo é analisar a quantidade de produtos vendidos em cada dia da semana, identificar qual produto teve o melhor desempenho e qual teve o pior, além de calcular a média de vendas diárias e a variação entre os dias da semana. 

### Importação da biblioteca

In [2]:
import numpy as np

In [3]:
# criação da matriz com as vendas da semana
vendas_semana = np.array([
    [12, 10, 8, 6],
    [18, 15, 12, 10],
    [10, 8, 5, 3],
    [22, 20, 18, 16],
    [15, 12, 10, 8]
])

### Qual o total de vendas em cada dia da semana?

In [8]:
vendas_no_dia = np.sum(vendas_semana, axis=1) 
print(vendas_no_dia)

[36 55 26 76 45]


### Qual o total de vendas de cada produto?

In [9]:
vendas_produtos = np.sum(vendas_semana, axis=0)
print(vendas_produtos)

[77 65 53 43]


### Qual a média de vendas por dia da semana?

In [10]:
media_vendas = np.mean(vendas_semana, axis=0)
print(media_vendas)

[15.4 13.  10.6  8.6]


### Qual o produto com menor variação nas vendas ao longo da semana?

In [23]:
variacao = np.std(vendas_semana, axis=0)
min_variacao = np.argmin(variacao)
print(f'Variação dos produtos: {variacao}\n')
print(f'Produto {min_variacao + 1} apresentou a maior variação de vendas.')

Variação dos produtos: [4.2708313  4.19523539 4.36348485 4.36348485]

Produto 2 apresentou a maior variação de vendas.


### Identificar o produto com maior e menor vendas na semana

In [25]:
maior_venda = np.argmax(np.sum(vendas_semana, axis=0))
menor_venda = np.argmin(np.sum(vendas_semana, axis=0))

print("Produto com maior venda: Produto", maior_venda+1)
print("Produto com menor venda: Produto", menor_venda+1)

### Calcular a média de vendas diárias e variação entre os dias da semana

In [28]:
media_vendas_diarias = np.mean(vendas_semana, axis=1)
var_vendas_diarias = np.var(vendas_semana, axis=1)

print("Média de vendas diárias: ", media_vendas_diarias)
print("Variação de vendas diárias: ", var_vendas_diarias)

Média de vendas diárias:  [ 9.   13.75  6.5  19.   11.25]
Variação de vendas diárias:  [5.     9.1875 7.25   5.     6.6875]
